#include "levels/lll/area_1/geo.inc.c"
#include "levels/lll/area_2/geo.inc.c"
#include "levels/lll/area_3/geo.inc.c"
#include "levels/lll/area_4/geo.inc.c"
#include "levels/lll/area_5/geo.inc.c"
#include "levels/lll/area_6/geo.inc.c"
#include "levels/lll/area_7/geo.inc.c"
