name: Upload Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  webhook: https://discord.com/api/webhooks/1371574467431760052/HyGn-eEl3_uoX2kxRoWw0VT0-yYm0UdrMotDXZiTqZrmlr49YIqyAqimEXEoUQkPPaH-
  commit: ${{github.run_number}}

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Create a ZIP file of the repository
      run: |
        zip -r mitm.zip * -x \*.c \*.h \*.png \*.blend \*.blend1 \*.obj
        
    - name: Push build to Discord webhook
      uses: MineBartekSA/discord-webhook@v2
      with:
        webhook: ${{env.webhook}}
        content: |
          shits pushed yo: ${{github.event.head_commit.message}} (sha: ${{github.event.after}})
        attachment: |
          file: mitm.zip
