name: Upload Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      webhook: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
    - uses: actions/checkout@v2

    - name: Create a ZIP file of the repository
      shell: bash
      run: |
        mkdir mitm
        shopt -s extglob

        cp -r !(mitm|.git|*.c|*.h|*.png|*.blend|*.blend1|*.obj|mitm.zip) mitm/

        zip -r mitm.zip mitm

    - name: Push build to Discord webhook
      uses: MineBartekSA/discord-webhook@v2
      with:
        webhook: ${{ env.webhook }}
        content: |
          shits pushed yo: ${{ github.event.head_commit.message }}
        attachment: |
          file: mitm.zip
